### ISSUE TITLE
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by jeleecarex** [goshng/polap#1]
I have the following error massage when installing your conda package. thanks!

> Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)

**Comment by goshng** [comment]
It is hard to reproduce the error. Sorry for this issue, and I have to close it. Thank you.
