### ISSUE TITLE
Clarification Needed for Columns V3, V4, V5, V7, and V8 in Organelle Gene Annotation File

### ISSUE THREAD

**Issue by jeleecarex** [goshng/polap#2]
Hello,

I am currently working with the organelle gene annotation file produced by the POLAP pipeline and need clarification on several columns, specifically **V3, V4, V5, V7, and V8**. While I understand the general structure of the file, the exact meaning of these columns is unclear. Additionally, in V8, some entries display * while others have numeric values, and I’m unsure whether these numeric values should be included in contig selection.

For example, here is an excerpt from my file:

```
Contig       Length  V3    V4  V5  Copy  V7     V8  MT  PT  Edge
contig_132   3292    379   N   Y   95    none   *   2   3   132
contig_131   733     383   Y   Y   96    none   2   0   0   131
contig_153   687     488   Y   Y   122   none   4   0   0   153
```

Could you please clarify:

The meaning and significance of columns V3, V4, V5, V7, and V8.
If numeric values in V8 (as opposed to *) should be considered for contig selection.
This information would greatly assist in accurately filtering and selecting contigs for further analysis.

Thank you for your assistance!

**Comment by goshng** [comment]
I am sorry for not responding to your question.

They are from Flye's output: assembly_info.txt or  contigs_stats.txt. I do not use those for contig seed selection, and did not name them. I should have used the same name as Flye's. In short, they are document at 

https://github.com/mikolmogorov/Flye/blob/flye/docs/USAGE.md#-flye-output

- V3: Coverage
- V4: Is circular, (Y)es or (N)o
- V5: Is repetitive, (Y)es or (N)o
- Copy: Multiplicity (based on coverage)
- V7: Alternative group
- V8: Graph path (graph path corresponding to this contig/scaffold).

I hope that this might be helpful.

Thank you!

**Comment by goshng** [comment]
I have updated the format of the annotation table. So, this would not be an issue any more. Thank you.
